development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: dbuser
  password: dbuser
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username: dbuser
  password: dbuser
  host: localhost
  port: 5432
